	modLoader="javafml" 
	loaderVersion="[36,)"
	license="MIT License"



[[mods]] 

	modId="oceanventure" 
	version="${file.jarVersion}" 
	displayName="ToastKun" 
	logoFile="logo.png" 
	credits="ToastKun"
	authors="SJKZ1" 
	description='''A special mod for ToastKun'''



[[dependencies.oceanventure]] 

		modId="forge" 
		mandatory=true 
		versionRange="[36.1.2,)" 
		ordering="NONE"
		side="BOTH"
		
[[dependencies.oceanventure]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.16.5]"
		ordering="NONE"
		side="BOTH"