	modLoader="javafml" 
	loaderVersion="[35,)"
	license="MIT License"
	updateJSONURL="https://raw.githubusercontent.com/SJKZ1-2565/ToastKun/master/CHANGELOG"


[[mods]] 

	modId="toastkun" 
	version="${file.jarVersion}" 
	displayName="ToastKun" 
	#displayURL="https://www.curseforge.com/minecraft/mc-mods/mcbreaker"
	logoFile="logo.png" 
	credits="ToastKun"
	authors="SJKZ1" 
	description='''An special mod for ToastKun'''



[[dependencies.toastkun]] 

		modId="forge" 
		mandatory=true 
		versionRange="[35.1.0,)" 
		ordering="NONE"
		side="BOTH"
		
[[dependencies.toastkun]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.16.4]"
		ordering="NONE"
		side="BOTH"